# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Thomas\Documents\GitHub\Calabash-Tools\src\calabash\scripts\calabash\views\UI\playblast.ui'
#
# Created: Sat Feb 17 00:21:50 2018
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_playblast_dlg(object):
    def setupUi(self, playblast_dlg):
        playblast_dlg.setObjectName("playblast_dlg")
        playblast_dlg.resize(400, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(playblast_dlg.sizePolicy().hasHeightForWidth())
        playblast_dlg.setSizePolicy(sizePolicy)
        playblast_dlg.setMinimumSize(QtCore.QSize(400, 300))
        playblast_dlg.setMaximumSize(QtCore.QSize(400, 300))
        self.main_vlt = QtWidgets.QVBoxLayout(playblast_dlg)
        self.main_vlt.setSpacing(4)
        self.main_vlt.setContentsMargins(6, 6, 6, 6)
        self.main_vlt.setObjectName("main_vlt")
        self.playblast_vlt = QtWidgets.QVBoxLayout()
        self.playblast_vlt.setSpacing(4)
        self.playblast_vlt.setContentsMargins(-1, -1, -1, 10)
        self.playblast_vlt.setObjectName("playblast_vlt")
        self.title_hlt = QtWidgets.QHBoxLayout()
        self.title_hlt.setContentsMargins(-1, -1, -1, 8)
        self.title_hlt.setObjectName("title_hlt")
        self.title_lbl = QtWidgets.QLabel(playblast_dlg)
        self.title_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.title_lbl.setObjectName("title_lbl")
        self.title_hlt.addWidget(self.title_lbl)
        self.playblast_vlt.addLayout(self.title_hlt)
        self.line = QtWidgets.QFrame(playblast_dlg)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.playblast_vlt.addWidget(self.line)
        self.filename_hlt = QtWidgets.QHBoxLayout()
        self.filename_hlt.setSpacing(4)
        self.filename_hlt.setObjectName("filename_hlt")
        self.filename_lbl = QtWidgets.QLabel(playblast_dlg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filename_lbl.sizePolicy().hasHeightForWidth())
        self.filename_lbl.setSizePolicy(sizePolicy)
        self.filename_lbl.setMinimumSize(QtCore.QSize(100, 0))
        self.filename_lbl.setMaximumSize(QtCore.QSize(150, 16777215))
        self.filename_lbl.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.filename_lbl.setObjectName("filename_lbl")
        self.filename_hlt.addWidget(self.filename_lbl)
        self.filename_le = QtWidgets.QLineEdit(playblast_dlg)
        self.filename_le.setEnabled(False)
        self.filename_le.setReadOnly(False)
        self.filename_le.setObjectName("filename_le")
        self.filename_hlt.addWidget(self.filename_le)
        self.playblast_vlt.addLayout(self.filename_hlt)
        self.line_2 = QtWidgets.QFrame(playblast_dlg)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.playblast_vlt.addWidget(self.line_2)
        self.widthHeight_hlt = QtWidgets.QHBoxLayout()
        self.widthHeight_hlt.setSpacing(4)
        self.widthHeight_hlt.setObjectName("widthHeight_hlt")
        self.widthHeight_lbl = QtWidgets.QLabel(playblast_dlg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widthHeight_lbl.sizePolicy().hasHeightForWidth())
        self.widthHeight_lbl.setSizePolicy(sizePolicy)
        self.widthHeight_lbl.setMinimumSize(QtCore.QSize(100, 0))
        self.widthHeight_lbl.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.widthHeight_lbl.setObjectName("widthHeight_lbl")
        self.widthHeight_hlt.addWidget(self.widthHeight_lbl)
        self.width_le = QtWidgets.QLineEdit(playblast_dlg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.width_le.sizePolicy().hasHeightForWidth())
        self.width_le.setSizePolicy(sizePolicy)
        self.width_le.setMaximumSize(QtCore.QSize(50, 16777215))
        self.width_le.setObjectName("width_le")
        self.widthHeight_hlt.addWidget(self.width_le)
        self.height_le = QtWidgets.QLineEdit(playblast_dlg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.height_le.sizePolicy().hasHeightForWidth())
        self.height_le.setSizePolicy(sizePolicy)
        self.height_le.setMaximumSize(QtCore.QSize(50, 16777215))
        self.height_le.setObjectName("height_le")
        self.widthHeight_hlt.addWidget(self.height_le)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.widthHeight_hlt.addItem(spacerItem)
        self.playblast_vlt.addLayout(self.widthHeight_hlt)
        self.startEnd_hlt = QtWidgets.QHBoxLayout()
        self.startEnd_hlt.setSpacing(4)
        self.startEnd_hlt.setObjectName("startEnd_hlt")
        self.startEnd_lbl = QtWidgets.QLabel(playblast_dlg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startEnd_lbl.sizePolicy().hasHeightForWidth())
        self.startEnd_lbl.setSizePolicy(sizePolicy)
        self.startEnd_lbl.setMinimumSize(QtCore.QSize(100, 0))
        self.startEnd_lbl.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.startEnd_lbl.setObjectName("startEnd_lbl")
        self.startEnd_hlt.addWidget(self.startEnd_lbl)
        self.start_le = QtWidgets.QLineEdit(playblast_dlg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start_le.sizePolicy().hasHeightForWidth())
        self.start_le.setSizePolicy(sizePolicy)
        self.start_le.setMaximumSize(QtCore.QSize(50, 16777215))
        self.start_le.setObjectName("start_le")
        self.startEnd_hlt.addWidget(self.start_le)
        self.end_le = QtWidgets.QLineEdit(playblast_dlg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.end_le.sizePolicy().hasHeightForWidth())
        self.end_le.setSizePolicy(sizePolicy)
        self.end_le.setMaximumSize(QtCore.QSize(50, 16777215))
        self.end_le.setObjectName("end_le")
        self.startEnd_hlt.addWidget(self.end_le)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.startEnd_hlt.addItem(spacerItem1)
        self.playblast_vlt.addLayout(self.startEnd_hlt)
        self.line_3 = QtWidgets.QFrame(playblast_dlg)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.playblast_vlt.addWidget(self.line_3)
        self.hud_chk = QtWidgets.QCheckBox(playblast_dlg)
        self.hud_chk.setChecked(True)
        self.hud_chk.setObjectName("hud_chk")
        self.playblast_vlt.addWidget(self.hud_chk)
        self.cstmHud_hlt = QtWidgets.QHBoxLayout()
        self.cstmHud_hlt.setSpacing(4)
        self.cstmHud_hlt.setObjectName("cstmHud_hlt")
        self.cstmHud_chk = QtWidgets.QCheckBox(playblast_dlg)
        self.cstmHud_chk.setObjectName("cstmHud_chk")
        self.cstmHud_hlt.addWidget(self.cstmHud_chk)
        self.cstmHud_le = QtWidgets.QLineEdit(playblast_dlg)
        self.cstmHud_le.setEnabled(False)
        self.cstmHud_le.setText("")
        self.cstmHud_le.setObjectName("cstmHud_le")
        self.cstmHud_hlt.addWidget(self.cstmHud_le)
        self.playblast_vlt.addLayout(self.cstmHud_hlt)
        self.line_4 = QtWidgets.QFrame(playblast_dlg)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.playblast_vlt.addWidget(self.line_4)
        self.clearViewport_chk = QtWidgets.QCheckBox(playblast_dlg)
        self.clearViewport_chk.setChecked(True)
        self.clearViewport_chk.setObjectName("clearViewport_chk")
        self.playblast_vlt.addWidget(self.clearViewport_chk)
        self.green_chk = QtWidgets.QCheckBox(playblast_dlg)
        self.green_chk.setObjectName("green_chk")
        self.playblast_vlt.addWidget(self.green_chk)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.playblast_vlt.addItem(spacerItem2)
        self.playblast_btn = QtWidgets.QPushButton(playblast_dlg)
        self.playblast_btn.setObjectName("playblast_btn")
        self.playblast_vlt.addWidget(self.playblast_btn)
        self.main_vlt.addLayout(self.playblast_vlt)
        self.filename_lbl.setBuddy(self.filename_le)
        self.widthHeight_lbl.setBuddy(self.width_le)
        self.startEnd_lbl.setBuddy(self.start_le)

        self.retranslateUi(playblast_dlg)
        QtCore.QMetaObject.connectSlotsByName(playblast_dlg)

    def retranslateUi(self, playblast_dlg):
        playblast_dlg.setWindowTitle(QtWidgets.QApplication.translate("playblast_dlg", "Playblast", None, -1))
        self.title_lbl.setText(QtWidgets.QApplication.translate("playblast_dlg", "Playblast", None, -1))
        self.filename_lbl.setText(QtWidgets.QApplication.translate("playblast_dlg", "Filename:", None, -1))
        self.widthHeight_lbl.setText(QtWidgets.QApplication.translate("playblast_dlg", "Width/Height", None, -1))
        self.width_le.setText(QtWidgets.QApplication.translate("playblast_dlg", "960", None, -1))
        self.height_le.setText(QtWidgets.QApplication.translate("playblast_dlg", "540", None, -1))
        self.startEnd_lbl.setText(QtWidgets.QApplication.translate("playblast_dlg", "Start/End Frame", None, -1))
        self.hud_chk.setText(QtWidgets.QApplication.translate("playblast_dlg", "HUD: Add Project, Scene, Frame Number", None, -1))
        self.cstmHud_chk.setText(QtWidgets.QApplication.translate("playblast_dlg", "HUD: Custom/Name", None, -1))
        self.cstmHud_le.setPlaceholderText(QtWidgets.QApplication.translate("playblast_dlg", "Enter Name...", None, -1))
        self.clearViewport_chk.setText(QtWidgets.QApplication.translate("playblast_dlg", "Clear Viewport", None, -1))
        self.green_chk.setText(QtWidgets.QApplication.translate("playblast_dlg", "Green Background", None, -1))
        self.playblast_btn.setText(QtWidgets.QApplication.translate("playblast_dlg", "Playblast!", None, -1))

