# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\tom4p\Dropbox\dev\goodtools\src\goodtools\scripts\goodPlayblast\UI\playblast04.ui'
#
# Created: Mon Apr 30 17:56:15 2018
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_playblast_dlg(object):
    def setupUi(self, playblast_dlg):
        playblast_dlg.setObjectName("playblast_dlg")
        playblast_dlg.setWindowModality(QtCore.Qt.WindowModal)
        playblast_dlg.resize(594, 650)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(playblast_dlg.sizePolicy().hasHeightForWidth())
        playblast_dlg.setSizePolicy(sizePolicy)
        playblast_dlg.setMinimumSize(QtCore.QSize(0, 650))
        playblast_dlg.setModal(False)
        self.main_vlt = QtWidgets.QVBoxLayout(playblast_dlg)
        self.main_vlt.setSpacing(4)
        self.main_vlt.setContentsMargins(6, 6, 6, 6)
        self.main_vlt.setObjectName("main_vlt")
        self.playblast_vlt = QtWidgets.QVBoxLayout()
        self.playblast_vlt.setSpacing(4)
        self.playblast_vlt.setContentsMargins(-1, -1, -1, 10)
        self.playblast_vlt.setObjectName("playblast_vlt")
        self.title_hlt = QtWidgets.QHBoxLayout()
        self.title_hlt.setContentsMargins(-1, -1, -1, 0)
        self.title_hlt.setObjectName("title_hlt")
        self.title_lbl = QtWidgets.QLabel(playblast_dlg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.title_lbl.sizePolicy().hasHeightForWidth())
        self.title_lbl.setSizePolicy(sizePolicy)
        self.title_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.title_lbl.setObjectName("title_lbl")
        self.title_hlt.addWidget(self.title_lbl)
        self.playblast_vlt.addLayout(self.title_hlt)
        self.frame = QtWidgets.QFrame(playblast_dlg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(0, 0))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_5.setSpacing(15)
        self.verticalLayout_5.setContentsMargins(4, 0, 4, 10)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.displayWidget = QtWidgets.QWidget(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.displayWidget.sizePolicy().hasHeightForWidth())
        self.displayWidget.setSizePolicy(sizePolicy)
        self.displayWidget.setMinimumSize(QtCore.QSize(0, 25))
        self.displayWidget.setObjectName("displayWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.displayWidget)
        self.verticalLayout_4.setSpacing(3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(-1, 5, -1, -1)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.line_2 = QtWidgets.QFrame(self.displayWidget)
        self.line_2.setMaximumSize(QtCore.QSize(20, 16777215))
        self.line_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_2.setLineWidth(0)
        self.line_2.setMidLineWidth(1)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_9.addWidget(self.line_2)
        self.label_12 = QtWidgets.QLabel(self.displayWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_9.addWidget(self.label_12)
        self.line_6 = QtWidgets.QFrame(self.displayWidget)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_6.setLineWidth(0)
        self.line_6.setMidLineWidth(1)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.horizontalLayout_9.addWidget(self.line_6)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.formLayout_5 = QtWidgets.QFormLayout()
        self.formLayout_5.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_5.setHorizontalSpacing(6)
        self.formLayout_5.setVerticalSpacing(3)
        self.formLayout_5.setObjectName("formLayout_5")
        self.overrideviewport_lbl = QtWidgets.QLabel(self.displayWidget)
        self.overrideviewport_lbl.setMinimumSize(QtCore.QSize(150, 0))
        self.overrideviewport_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.overrideviewport_lbl.setObjectName("overrideviewport_lbl")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.overrideviewport_lbl)
        self.viewportOverride_chk = QtWidgets.QCheckBox(self.displayWidget)
        self.viewportOverride_chk.setText("")
        self.viewportOverride_chk.setObjectName("viewportOverride_chk")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.viewportOverride_chk)
        self.onlyPolygons_lbl = QtWidgets.QLabel(self.displayWidget)
        self.onlyPolygons_lbl.setMinimumSize(QtCore.QSize(150, 0))
        self.onlyPolygons_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.onlyPolygons_lbl.setObjectName("onlyPolygons_lbl")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.onlyPolygons_lbl)
        self.onlyPolygons_chk = QtWidgets.QCheckBox(self.displayWidget)
        self.onlyPolygons_chk.setText("")
        self.onlyPolygons_chk.setChecked(False)
        self.onlyPolygons_chk.setObjectName("onlyPolygons_chk")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.onlyPolygons_chk)
        self.gates_chk = QtWidgets.QCheckBox(self.displayWidget)
        self.gates_chk.setText("")
        self.gates_chk.setObjectName("gates_chk")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.gates_chk)
        self.bgcolor_lbl = QtWidgets.QLabel(self.displayWidget)
        self.bgcolor_lbl.setMinimumSize(QtCore.QSize(150, 0))
        self.bgcolor_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.bgcolor_lbl.setObjectName("bgcolor_lbl")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.bgcolor_lbl)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(10)
        self.horizontalLayout_4.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.bgcolor_chk = QtWidgets.QCheckBox(self.displayWidget)
        self.bgcolor_chk.setText("")
        self.bgcolor_chk.setObjectName("bgcolor_chk")
        self.horizontalLayout_4.addWidget(self.bgcolor_chk)
        self.color_btn = QtWidgets.QPushButton(self.displayWidget)
        self.color_btn.setMaximumSize(QtCore.QSize(20, 15))
        self.color_btn.setText("")
        self.color_btn.setObjectName("color_btn")
        self.horizontalLayout_4.addWidget(self.color_btn)
        spacerItem = QtWidgets.QSpacerItem(40, 5, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.formLayout_5.setLayout(3, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_4)
        self.gates_lbl = QtWidgets.QLabel(self.displayWidget)
        self.gates_lbl.setMinimumSize(QtCore.QSize(150, 0))
        self.gates_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.gates_lbl.setObjectName("gates_lbl")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.gates_lbl)
        self.verticalLayout_4.addLayout(self.formLayout_5)
        self.verticalLayout_5.addWidget(self.displayWidget)
        self.hudWidget = QtWidgets.QWidget(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hudWidget.sizePolicy().hasHeightForWidth())
        self.hudWidget.setSizePolicy(sizePolicy)
        self.hudWidget.setMinimumSize(QtCore.QSize(0, 20))
        self.hudWidget.setObjectName("hudWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.hudWidget)
        self.verticalLayout_3.setSpacing(3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(-1, 5, -1, -1)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.line_7 = QtWidgets.QFrame(self.hudWidget)
        self.line_7.setMaximumSize(QtCore.QSize(20, 16777215))
        self.line_7.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_7.setLineWidth(0)
        self.line_7.setMidLineWidth(1)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.horizontalLayout_8.addWidget(self.line_7)
        self.label_11 = QtWidgets.QLabel(self.hudWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_8.addWidget(self.label_11)
        self.line = QtWidgets.QFrame(self.hudWidget)
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(0)
        self.line.setMidLineWidth(1)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_8.addWidget(self.line)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_4.setContentsMargins(-1, -1, 20, -1)
        self.formLayout_4.setVerticalSpacing(3)
        self.formLayout_4.setObjectName("formLayout_4")
        self.sceneinfohud_chk = QtWidgets.QLabel(self.hudWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sceneinfohud_chk.sizePolicy().hasHeightForWidth())
        self.sceneinfohud_chk.setSizePolicy(sizePolicy)
        self.sceneinfohud_chk.setMinimumSize(QtCore.QSize(150, 0))
        self.sceneinfohud_chk.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sceneinfohud_chk.setObjectName("sceneinfohud_chk")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.sceneinfohud_chk)
        self.namehud_lbl = QtWidgets.QLabel(self.hudWidget)
        self.namehud_lbl.setMinimumSize(QtCore.QSize(150, 0))
        self.namehud_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.namehud_lbl.setObjectName("namehud_lbl")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.namehud_lbl)
        self.cstmHud_hlt = QtWidgets.QHBoxLayout()
        self.cstmHud_hlt.setSpacing(4)
        self.cstmHud_hlt.setObjectName("cstmHud_hlt")
        self.cstmHud_chk = QtWidgets.QCheckBox(self.hudWidget)
        self.cstmHud_chk.setText("")
        self.cstmHud_chk.setObjectName("cstmHud_chk")
        self.cstmHud_hlt.addWidget(self.cstmHud_chk)
        self.cstmHud_le = QtWidgets.QLineEdit(self.hudWidget)
        self.cstmHud_le.setEnabled(True)
        self.cstmHud_le.setMinimumSize(QtCore.QSize(250, 0))
        self.cstmHud_le.setMaximumSize(QtCore.QSize(250, 16777215))
        self.cstmHud_le.setText("")
        self.cstmHud_le.setObjectName("cstmHud_le")
        self.cstmHud_hlt.addWidget(self.cstmHud_le)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.cstmHud_hlt.addItem(spacerItem1)
        self.formLayout_4.setLayout(3, QtWidgets.QFormLayout.FieldRole, self.cstmHud_hlt)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.line_4 = QtWidgets.QFrame(self.hudWidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_6.addWidget(self.line_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(0, 0, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setObjectName("gridLayout")
        self.frameHud_chk = QtWidgets.QCheckBox(self.hudWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameHud_chk.sizePolicy().hasHeightForWidth())
        self.frameHud_chk.setSizePolicy(sizePolicy)
        self.frameHud_chk.setMinimumSize(QtCore.QSize(120, 0))
        self.frameHud_chk.setObjectName("frameHud_chk")
        self.gridLayout.addWidget(self.frameHud_chk, 1, 0, 1, 1)
        self.scenehud_chk = QtWidgets.QCheckBox(self.hudWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scenehud_chk.sizePolicy().hasHeightForWidth())
        self.scenehud_chk.setSizePolicy(sizePolicy)
        self.scenehud_chk.setMinimumSize(QtCore.QSize(120, 0))
        self.scenehud_chk.setObjectName("scenehud_chk")
        self.gridLayout.addWidget(self.scenehud_chk, 0, 1, 1, 1)
        self.hud_chk = QtWidgets.QCheckBox(self.hudWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hud_chk.sizePolicy().hasHeightForWidth())
        self.hud_chk.setSizePolicy(sizePolicy)
        self.hud_chk.setMinimumSize(QtCore.QSize(120, 0))
        self.hud_chk.setChecked(False)
        self.hud_chk.setObjectName("hud_chk")
        self.gridLayout.addWidget(self.hud_chk, 0, 0, 1, 1)
        self.camerahud_chk = QtWidgets.QCheckBox(self.hudWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.camerahud_chk.sizePolicy().hasHeightForWidth())
        self.camerahud_chk.setSizePolicy(sizePolicy)
        self.camerahud_chk.setMinimumSize(QtCore.QSize(120, 0))
        self.camerahud_chk.setObjectName("camerahud_chk")
        self.gridLayout.addWidget(self.camerahud_chk, 1, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.line_11 = QtWidgets.QFrame(self.hudWidget)
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.verticalLayout_6.addWidget(self.line_11)
        self.formLayout_4.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.verticalLayout_6)
        self.displayhud_lbl = QtWidgets.QLabel(self.hudWidget)
        self.displayhud_lbl.setMinimumSize(QtCore.QSize(150, 0))
        self.displayhud_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.displayhud_lbl.setObjectName("displayhud_lbl")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.displayhud_lbl)
        self.displayhud_chk = QtWidgets.QCheckBox(self.hudWidget)
        self.displayhud_chk.setText("")
        self.displayhud_chk.setObjectName("displayhud_chk")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.displayhud_chk)
        self.hudOverride_chk = QtWidgets.QCheckBox(self.hudWidget)
        self.hudOverride_chk.setText("")
        self.hudOverride_chk.setObjectName("hudOverride_chk")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.hudOverride_chk)
        self.overridehud_lbl = QtWidgets.QLabel(self.hudWidget)
        self.overridehud_lbl.setMinimumSize(QtCore.QSize(150, 0))
        self.overridehud_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.overridehud_lbl.setObjectName("overridehud_lbl")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.overridehud_lbl)
        self.verticalLayout_3.addLayout(self.formLayout_4)
        self.verticalLayout_5.addWidget(self.hudWidget)
        self.formatWidget = QtWidgets.QWidget(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.formatWidget.sizePolicy().hasHeightForWidth())
        self.formatWidget.setSizePolicy(sizePolicy)
        self.formatWidget.setMinimumSize(QtCore.QSize(0, 25))
        self.formatWidget.setObjectName("formatWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.formatWidget)
        self.verticalLayout_2.setSpacing(3)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(-1, 5, -1, -1)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.line_8 = QtWidgets.QFrame(self.formatWidget)
        self.line_8.setMaximumSize(QtCore.QSize(20, 16777215))
        self.line_8.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_8.setLineWidth(0)
        self.line_8.setMidLineWidth(1)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.horizontalLayout_7.addWidget(self.line_8)
        self.label_10 = QtWidgets.QLabel(self.formatWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_7.addWidget(self.label_10)
        self.line_3 = QtWidgets.QFrame(self.formatWidget)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_3.setLineWidth(0)
        self.line_3.setMidLineWidth(1)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_7.addWidget(self.line_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setVerticalSpacing(3)
        self.formLayout_3.setObjectName("formLayout_3")
        self.widthHeight_lbl = QtWidgets.QLabel(self.formatWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widthHeight_lbl.sizePolicy().hasHeightForWidth())
        self.widthHeight_lbl.setSizePolicy(sizePolicy)
        self.widthHeight_lbl.setMinimumSize(QtCore.QSize(150, 0))
        self.widthHeight_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.widthHeight_lbl.setObjectName("widthHeight_lbl")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.widthHeight_lbl)
        self.startEnd_lbl = QtWidgets.QLabel(self.formatWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startEnd_lbl.sizePolicy().hasHeightForWidth())
        self.startEnd_lbl.setSizePolicy(sizePolicy)
        self.startEnd_lbl.setMinimumSize(QtCore.QSize(150, 0))
        self.startEnd_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.startEnd_lbl.setObjectName("startEnd_lbl")
        self.formLayout_3.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.startEnd_lbl)
        self.startEnd_hlt = QtWidgets.QHBoxLayout()
        self.startEnd_hlt.setSpacing(4)
        self.startEnd_hlt.setObjectName("startEnd_hlt")
        self.start_le = QtWidgets.QLineEdit(self.formatWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start_le.sizePolicy().hasHeightForWidth())
        self.start_le.setSizePolicy(sizePolicy)
        self.start_le.setMaximumSize(QtCore.QSize(40, 16777215))
        self.start_le.setObjectName("start_le")
        self.startEnd_hlt.addWidget(self.start_le)
        self.end_le = QtWidgets.QLineEdit(self.formatWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.end_le.sizePolicy().hasHeightForWidth())
        self.end_le.setSizePolicy(sizePolicy)
        self.end_le.setMaximumSize(QtCore.QSize(40, 16777215))
        self.end_le.setObjectName("end_le")
        self.startEnd_hlt.addWidget(self.end_le)
        self.loadRenderFrameRange_btn = QtWidgets.QPushButton(self.formatWidget)
        self.loadRenderFrameRange_btn.setMinimumSize(QtCore.QSize(200, 20))
        self.loadRenderFrameRange_btn.setMaximumSize(QtCore.QSize(16777215, 24))
        self.loadRenderFrameRange_btn.setObjectName("loadRenderFrameRange_btn")
        self.startEnd_hlt.addWidget(self.loadRenderFrameRange_btn)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.startEnd_hlt.addItem(spacerItem3)
        self.formLayout_3.setLayout(6, QtWidgets.QFormLayout.FieldRole, self.startEnd_hlt)
        self.label_2 = QtWidgets.QLabel(self.formatWidget)
        self.label_2.setMinimumSize(QtCore.QSize(150, 0))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.scale_le = QtWidgets.QLineEdit(self.formatWidget)
        self.scale_le.setMaximumSize(QtCore.QSize(40, 16777215))
        self.scale_le.setObjectName("scale_le")
        self.horizontalLayout_11.addWidget(self.scale_le)
        self.scale_sld = QtWidgets.QSlider(self.formatWidget)
        self.scale_sld.setMinimumSize(QtCore.QSize(195, 0))
        self.scale_sld.setOrientation(QtCore.Qt.Horizontal)
        self.scale_sld.setObjectName("scale_sld")
        self.horizontalLayout_11.addWidget(self.scale_sld)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem4)
        self.formLayout_3.setLayout(5, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_11)
        self.label_3 = QtWidgets.QLabel(self.formatWidget)
        self.label_3.setMinimumSize(QtCore.QSize(150, 0))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtWidgets.QLabel(self.formatWidget)
        self.label_4.setMinimumSize(QtCore.QSize(150, 0))
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_6 = QtWidgets.QLabel(self.formatWidget)
        self.label_6.setMinimumSize(QtCore.QSize(150, 0))
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.format_cmb = QtWidgets.QComboBox(self.formatWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.format_cmb.sizePolicy().hasHeightForWidth())
        self.format_cmb.setSizePolicy(sizePolicy)
        self.format_cmb.setMinimumSize(QtCore.QSize(150, 0))
        self.format_cmb.setMaximumSize(QtCore.QSize(150, 16777215))
        self.format_cmb.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.format_cmb.setObjectName("format_cmb")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.format_cmb)
        self.encoding_cmb = QtWidgets.QComboBox(self.formatWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.encoding_cmb.sizePolicy().hasHeightForWidth())
        self.encoding_cmb.setSizePolicy(sizePolicy)
        self.encoding_cmb.setMinimumSize(QtCore.QSize(150, 0))
        self.encoding_cmb.setMaximumSize(QtCore.QSize(150, 16777215))
        self.encoding_cmb.setObjectName("encoding_cmb")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.encoding_cmb)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.quality_le = QtWidgets.QLineEdit(self.formatWidget)
        self.quality_le.setMaximumSize(QtCore.QSize(40, 16777215))
        self.quality_le.setObjectName("quality_le")
        self.horizontalLayout_12.addWidget(self.quality_le)
        self.quality_sld = QtWidgets.QSlider(self.formatWidget)
        self.quality_sld.setMinimumSize(QtCore.QSize(195, 0))
        self.quality_sld.setOrientation(QtCore.Qt.Horizontal)
        self.quality_sld.setObjectName("quality_sld")
        self.horizontalLayout_12.addWidget(self.quality_sld)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem5)
        self.formLayout_3.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_12)
        self.widthHeight_hlt = QtWidgets.QHBoxLayout()
        self.widthHeight_hlt.setSpacing(4)
        self.widthHeight_hlt.setObjectName("widthHeight_hlt")
        self.customresolution_chk = QtWidgets.QCheckBox(self.formatWidget)
        self.customresolution_chk.setObjectName("customresolution_chk")
        self.widthHeight_hlt.addWidget(self.customresolution_chk)
        self.width_le = QtWidgets.QLineEdit(self.formatWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.width_le.sizePolicy().hasHeightForWidth())
        self.width_le.setSizePolicy(sizePolicy)
        self.width_le.setMaximumSize(QtCore.QSize(40, 16777215))
        self.width_le.setText("")
        self.width_le.setObjectName("width_le")
        self.widthHeight_hlt.addWidget(self.width_le)
        self.height_le = QtWidgets.QLineEdit(self.formatWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.height_le.sizePolicy().hasHeightForWidth())
        self.height_le.setSizePolicy(sizePolicy)
        self.height_le.setMaximumSize(QtCore.QSize(40, 16777215))
        self.height_le.setText("")
        self.height_le.setObjectName("height_le")
        self.widthHeight_hlt.addWidget(self.height_le)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.widthHeight_hlt.addItem(spacerItem6)
        self.formLayout_3.setLayout(3, QtWidgets.QFormLayout.FieldRole, self.widthHeight_hlt)
        self.verticalLayout_2.addLayout(self.formLayout_3)
        self.verticalLayout_5.addWidget(self.formatWidget)
        self.filenameWidget = QtWidgets.QWidget(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filenameWidget.sizePolicy().hasHeightForWidth())
        self.filenameWidget.setSizePolicy(sizePolicy)
        self.filenameWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.filenameWidget.setObjectName("filenameWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.filenameWidget)
        self.verticalLayout.setSpacing(3)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(-1, 5, -1, -1)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.line_9 = QtWidgets.QFrame(self.filenameWidget)
        self.line_9.setMaximumSize(QtCore.QSize(20, 16777215))
        self.line_9.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_9.setLineWidth(0)
        self.line_9.setMidLineWidth(1)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.horizontalLayout_6.addWidget(self.line_9)
        self.label_9 = QtWidgets.QLabel(self.filenameWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_6.addWidget(self.label_9)
        self.line_5 = QtWidgets.QFrame(self.filenameWidget)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_5.setLineWidth(0)
        self.line_5.setMidLineWidth(1)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.horizontalLayout_6.addWidget(self.line_5)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setContentsMargins(-1, -1, 20, -1)
        self.formLayout_2.setVerticalSpacing(3)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_7 = QtWidgets.QLabel(self.filenameWidget)
        self.label_7.setMinimumSize(QtCore.QSize(150, 0))
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.offscreen_chk = QtWidgets.QCheckBox(self.filenameWidget)
        self.offscreen_chk.setText("")
        self.offscreen_chk.setObjectName("offscreen_chk")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.offscreen_chk)
        self.label_16 = QtWidgets.QLabel(self.filenameWidget)
        self.label_16.setMinimumSize(QtCore.QSize(150, 0))
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.view_chk = QtWidgets.QCheckBox(self.filenameWidget)
        self.view_chk.setText("")
        self.view_chk.setObjectName("view_chk")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.view_chk)
        self.label = QtWidgets.QLabel(self.filenameWidget)
        self.label.setMinimumSize(QtCore.QSize(150, 0))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label)
        self.overwrite_chk = QtWidgets.QCheckBox(self.filenameWidget)
        self.overwrite_chk.setText("")
        self.overwrite_chk.setObjectName("overwrite_chk")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.overwrite_chk)
        self.label_5 = QtWidgets.QLabel(self.filenameWidget)
        self.label_5.setMinimumSize(QtCore.QSize(150, 0))
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(9)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.saveDir_le = QtWidgets.QLineEdit(self.filenameWidget)
        self.saveDir_le.setMinimumSize(QtCore.QSize(250, 0))
        self.saveDir_le.setMaximumSize(QtCore.QSize(250, 16777215))
        self.saveDir_le.setObjectName("saveDir_le")
        self.horizontalLayout_5.addWidget(self.saveDir_le)
        self.browse_btn = QtWidgets.QPushButton(self.filenameWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.browse_btn.sizePolicy().hasHeightForWidth())
        self.browse_btn.setSizePolicy(sizePolicy)
        self.browse_btn.setMinimumSize(QtCore.QSize(120, 0))
        self.browse_btn.setMaximumSize(QtCore.QSize(120, 16777215))
        self.browse_btn.setObjectName("browse_btn")
        self.horizontalLayout_5.addWidget(self.browse_btn)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem7)
        self.formLayout_2.setLayout(3, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_5)
        self.filename_lbl = QtWidgets.QLabel(self.filenameWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filename_lbl.sizePolicy().hasHeightForWidth())
        self.filename_lbl.setSizePolicy(sizePolicy)
        self.filename_lbl.setMinimumSize(QtCore.QSize(150, 0))
        self.filename_lbl.setMaximumSize(QtCore.QSize(150, 16777215))
        self.filename_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.filename_lbl.setObjectName("filename_lbl")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.filename_lbl)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.filename_le = QtWidgets.QLineEdit(self.filenameWidget)
        self.filename_le.setEnabled(True)
        self.filename_le.setMinimumSize(QtCore.QSize(250, 0))
        self.filename_le.setMaximumSize(QtCore.QSize(250, 16777215))
        self.filename_le.setReadOnly(False)
        self.filename_le.setObjectName("filename_le")
        self.horizontalLayout_2.addWidget(self.filename_le)
        self.usescenename_chk = QtWidgets.QCheckBox(self.filenameWidget)
        self.usescenename_chk.setEnabled(True)
        self.usescenename_chk.setMinimumSize(QtCore.QSize(120, 0))
        self.usescenename_chk.setMaximumSize(QtCore.QSize(120, 16777215))
        self.usescenename_chk.setChecked(True)
        self.usescenename_chk.setObjectName("usescenename_chk")
        self.horizontalLayout_2.addWidget(self.usescenename_chk)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem8)
        self.formLayout_2.setLayout(4, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.filenamepreview_lbl = QtWidgets.QLabel(self.filenameWidget)
        self.filenamepreview_lbl.setEnabled(False)
        self.filenamepreview_lbl.setObjectName("filenamepreview_lbl")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.filenamepreview_lbl)
        self.verticalLayout.addLayout(self.formLayout_2)
        self.verticalLayout_5.addWidget(self.filenameWidget)
        self.playblast_vlt.addWidget(self.frame)
        spacerItem9 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.playblast_vlt.addItem(spacerItem9)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(20, 0, 20, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.playblast_btn = QtWidgets.QPushButton(playblast_dlg)
        self.playblast_btn.setObjectName("playblast_btn")
        self.horizontalLayout_3.addWidget(self.playblast_btn)
        self.save_btn = QtWidgets.QPushButton(playblast_dlg)
        self.save_btn.setMaximumSize(QtCore.QSize(125, 16777215))
        self.save_btn.setObjectName("save_btn")
        self.horizontalLayout_3.addWidget(self.save_btn)
        self.reset_btn = QtWidgets.QPushButton(playblast_dlg)
        self.reset_btn.setMaximumSize(QtCore.QSize(125, 16777215))
        self.reset_btn.setObjectName("reset_btn")
        self.horizontalLayout_3.addWidget(self.reset_btn)
        self.playblast_vlt.addLayout(self.horizontalLayout_3)
        self.main_vlt.addLayout(self.playblast_vlt)
        self.widthHeight_lbl.setBuddy(self.width_le)
        self.startEnd_lbl.setBuddy(self.start_le)
        self.filename_lbl.setBuddy(self.filename_le)

        self.retranslateUi(playblast_dlg)
        QtCore.QMetaObject.connectSlotsByName(playblast_dlg)

    def retranslateUi(self, playblast_dlg):
        playblast_dlg.setWindowTitle(QtWidgets.QApplication.translate("playblast_dlg", "Good Playblast Options", None, -1))
        self.title_lbl.setText(QtWidgets.QApplication.translate("playblast_dlg", "-- Good Playblast --", None, -1))
        self.label_12.setText(QtWidgets.QApplication.translate("playblast_dlg", "Display", None, -1))
        self.overrideviewport_lbl.setText(QtWidgets.QApplication.translate("playblast_dlg", "Override Viewport:", None, -1))
        self.onlyPolygons_lbl.setText(QtWidgets.QApplication.translate("playblast_dlg", "Only Polygons:", None, -1))
        self.bgcolor_lbl.setText(QtWidgets.QApplication.translate("playblast_dlg", "BG Color:", None, -1))
        self.gates_lbl.setText(QtWidgets.QApplication.translate("playblast_dlg", "Gates ON:", None, -1))
        self.label_11.setText(QtWidgets.QApplication.translate("playblast_dlg", "HUD", None, -1))
        self.sceneinfohud_chk.setText(QtWidgets.QApplication.translate("playblast_dlg", "Scene Info:", None, -1))
        self.namehud_lbl.setText(QtWidgets.QApplication.translate("playblast_dlg", "User Name:", None, -1))
        self.cstmHud_le.setPlaceholderText(QtWidgets.QApplication.translate("playblast_dlg", "Enter Name...", None, -1))
        self.frameHud_chk.setText(QtWidgets.QApplication.translate("playblast_dlg", "Frame Counter", None, -1))
        self.scenehud_chk.setText(QtWidgets.QApplication.translate("playblast_dlg", "Scene", None, -1))
        self.hud_chk.setText(QtWidgets.QApplication.translate("playblast_dlg", "Project", None, -1))
        self.camerahud_chk.setText(QtWidgets.QApplication.translate("playblast_dlg", "Camera", None, -1))
        self.displayhud_lbl.setText(QtWidgets.QApplication.translate("playblast_dlg", "HUD ON:", None, -1))
        self.overridehud_lbl.setText(QtWidgets.QApplication.translate("playblast_dlg", "Override Scene HUD:", None, -1))
        self.label_10.setText(QtWidgets.QApplication.translate("playblast_dlg", "Format", None, -1))
        self.widthHeight_lbl.setText(QtWidgets.QApplication.translate("playblast_dlg", "Width/Height:", None, -1))
        self.startEnd_lbl.setText(QtWidgets.QApplication.translate("playblast_dlg", "Start/End:", None, -1))
        self.loadRenderFrameRange_btn.setText(QtWidgets.QApplication.translate("playblast_dlg", "Load from Render Settings", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("playblast_dlg", "Scale:", None, -1))
        self.scale_le.setText(QtWidgets.QApplication.translate("playblast_dlg", "0", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("playblast_dlg", "Format:", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("playblast_dlg", "Encoding:", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("playblast_dlg", "Quality", None, -1))
        self.quality_le.setText(QtWidgets.QApplication.translate("playblast_dlg", "0", None, -1))
        self.customresolution_chk.setText(QtWidgets.QApplication.translate("playblast_dlg", "Custom Resolution", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("playblast_dlg", "Save", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("playblast_dlg", "Playblast Offscreen:", None, -1))
        self.label_16.setText(QtWidgets.QApplication.translate("playblast_dlg", "View:", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("playblast_dlg", "Overwrite:", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("playblast_dlg", "Save Directory:", None, -1))
        self.browse_btn.setText(QtWidgets.QApplication.translate("playblast_dlg", "Browse", None, -1))
        self.filename_lbl.setText(QtWidgets.QApplication.translate("playblast_dlg", "Filename:", None, -1))
        self.usescenename_chk.setText(QtWidgets.QApplication.translate("playblast_dlg", "Use Scene Name", None, -1))
        self.filenamepreview_lbl.setText(QtWidgets.QApplication.translate("playblast_dlg", "filepath/filename preview", None, -1))
        self.playblast_btn.setText(QtWidgets.QApplication.translate("playblast_dlg", "Playblast!", None, -1))
        self.save_btn.setText(QtWidgets.QApplication.translate("playblast_dlg", "Save Settings", None, -1))
        self.reset_btn.setText(QtWidgets.QApplication.translate("playblast_dlg", "Reset", None, -1))

