# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\guest1\Documents\maya\modules\calabash\scripts\pipeman\anim_autocache_ui.ui'
#
# Created: Wed Mar 27 16:34:33 2019
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_mainUI(object):
    def setupUi(self, mainUI):
        mainUI.setObjectName("mainUI")
        mainUI.resize(560, 381)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mainUI.sizePolicy().hasHeightForWidth())
        mainUI.setSizePolicy(sizePolicy)
        mainUI.setMinimumSize(QtCore.QSize(560, 300))
        mainUI.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.gridLayout = QtWidgets.QGridLayout(mainUI)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(mainUI)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.line = QtWidgets.QFrame(mainUI)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(mainUI)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        spacerItem = QtWidgets.QSpacerItem(65, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.lineEdit_Path_Anim = QtWidgets.QLineEdit(mainUI)
        self.lineEdit_Path_Anim.setObjectName("lineEdit_Path_Anim")
        self.horizontalLayout_4.addWidget(self.lineEdit_Path_Anim)
        self.pushButton_Browse_Anim = QtWidgets.QPushButton(mainUI)
        self.pushButton_Browse_Anim.setObjectName("pushButton_Browse_Anim")
        self.horizontalLayout_4.addWidget(self.pushButton_Browse_Anim)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.label_6 = QtWidgets.QLabel(mainUI)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_7.addWidget(self.label_6)
        self.lineEdit_FrameStart = QtWidgets.QLineEdit(mainUI)
        self.lineEdit_FrameStart.setMaximumSize(QtCore.QSize(25, 16777215))
        self.lineEdit_FrameStart.setObjectName("lineEdit_FrameStart")
        self.horizontalLayout_7.addWidget(self.lineEdit_FrameStart)
        self.label_7 = QtWidgets.QLabel(mainUI)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.lineEdit_FrameEnd = QtWidgets.QLineEdit(mainUI)
        self.lineEdit_FrameEnd.setMaximumSize(QtCore.QSize(25, 16777215))
        self.lineEdit_FrameEnd.setObjectName("lineEdit_FrameEnd")
        self.horizontalLayout_7.addWidget(self.lineEdit_FrameEnd)
        spacerItem2 = QtWidgets.QSpacerItem(85, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(mainUI)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        spacerItem3 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.lineEdit_Path_Pub = QtWidgets.QLineEdit(mainUI)
        self.lineEdit_Path_Pub.setObjectName("lineEdit_Path_Pub")
        self.horizontalLayout_3.addWidget(self.lineEdit_Path_Pub)
        self.pushButton_Browse_Pub = QtWidgets.QPushButton(mainUI)
        self.pushButton_Browse_Pub.setObjectName("pushButton_Browse_Pub")
        self.horizontalLayout_3.addWidget(self.pushButton_Browse_Pub)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_AddTargets = QtWidgets.QPushButton(mainUI)
        self.pushButton_AddTargets.setObjectName("pushButton_AddTargets")
        self.verticalLayout_2.addWidget(self.pushButton_AddTargets)
        self.listWidget_targets = QtWidgets.QListWidget(mainUI)
        self.listWidget_targets.setObjectName("listWidget_targets")
        self.verticalLayout_2.addWidget(self.listWidget_targets)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_5 = QtWidgets.QLabel(mainUI)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_6.addWidget(self.label_5)
        spacerItem4 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.lineEdit_Path_DoIt = QtWidgets.QLineEdit(mainUI)
        self.lineEdit_Path_DoIt.setObjectName("lineEdit_Path_DoIt")
        self.horizontalLayout_6.addWidget(self.lineEdit_Path_DoIt)
        self.pushButton_Browse_DoIt = QtWidgets.QPushButton(mainUI)
        self.pushButton_Browse_DoIt.setObjectName("pushButton_Browse_DoIt")
        self.horizontalLayout_6.addWidget(self.pushButton_Browse_DoIt)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.pushButton_DoIt = QtWidgets.QPushButton(mainUI)
        self.pushButton_DoIt.setObjectName("pushButton_DoIt")
        self.horizontalLayout_5.addWidget(self.pushButton_DoIt)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 2, 2)

        self.retranslateUi(mainUI)
        QtCore.QMetaObject.connectSlotsByName(mainUI)

    def retranslateUi(self, mainUI):
        mainUI.setWindowTitle(QtWidgets.QApplication.translate("mainUI", "Animation Autocache", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("mainUI", "Do it Button 3000", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("mainUI", "Animation Directory", None, -1))
        self.pushButton_Browse_Anim.setText(QtWidgets.QApplication.translate("mainUI", "Browse", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("mainUI", "Frame Start:", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("mainUI", "Frame End:", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("mainUI", "Published Animation Directory", None, -1))
        self.pushButton_Browse_Pub.setText(QtWidgets.QApplication.translate("mainUI", "Browse", None, -1))
        self.pushButton_AddTargets.setText(QtWidgets.QApplication.translate("mainUI", "Add Targets From Selection", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("mainUI", "Batch file Location", None, -1))
        self.pushButton_Browse_DoIt.setText(QtWidgets.QApplication.translate("mainUI", "Browse", None, -1))
        self.pushButton_DoIt.setText(QtWidgets.QApplication.translate("mainUI", "Do It!", None, -1))

