# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Thomas\Documents\GitHub\Calabash-Tools\src\calabash\scripts\calabash\playblast\UI\playblast02.ui'
#
# Created: Sat Mar 03 00:44:33 2018
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_playblast_dlg(object):
    def setupUi(self, playblast_dlg):
        playblast_dlg.setObjectName("playblast_dlg")
        playblast_dlg.resize(600, 459)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(playblast_dlg.sizePolicy().hasHeightForWidth())
        playblast_dlg.setSizePolicy(sizePolicy)
        self.main_vlt = QtWidgets.QVBoxLayout(playblast_dlg)
        self.main_vlt.setSpacing(4)
        self.main_vlt.setContentsMargins(6, 6, 6, 6)
        self.main_vlt.setObjectName("main_vlt")
        self.playblast_vlt = QtWidgets.QVBoxLayout()
        self.playblast_vlt.setSpacing(4)
        self.playblast_vlt.setContentsMargins(-1, -1, -1, 10)
        self.playblast_vlt.setObjectName("playblast_vlt")
        self.title_hlt = QtWidgets.QHBoxLayout()
        self.title_hlt.setContentsMargins(-1, -1, -1, 8)
        self.title_hlt.setObjectName("title_hlt")
        self.title_lbl = QtWidgets.QLabel(playblast_dlg)
        self.title_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.title_lbl.setObjectName("title_lbl")
        self.title_hlt.addWidget(self.title_lbl)
        self.playblast_vlt.addLayout(self.title_hlt)
        self.filename_hlt = QtWidgets.QHBoxLayout()
        self.filename_hlt.setSpacing(4)
        self.filename_hlt.setObjectName("filename_hlt")
        self.playblast_vlt.addLayout(self.filename_hlt)
        self.line_4 = QtWidgets.QFrame(playblast_dlg)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.playblast_vlt.addWidget(self.line_4)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayout.setContentsMargins(20, 0, 20, -1)
        self.formLayout.setVerticalSpacing(10)
        self.formLayout.setObjectName("formLayout")
        self.filename_lbl = QtWidgets.QLabel(playblast_dlg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filename_lbl.sizePolicy().hasHeightForWidth())
        self.filename_lbl.setSizePolicy(sizePolicy)
        self.filename_lbl.setMinimumSize(QtCore.QSize(120, 0))
        self.filename_lbl.setMaximumSize(QtCore.QSize(150, 16777215))
        self.filename_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.filename_lbl.setObjectName("filename_lbl")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.filename_lbl)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.filename_le = QtWidgets.QLineEdit(playblast_dlg)
        self.filename_le.setEnabled(True)
        self.filename_le.setMaximumSize(QtCore.QSize(250, 16777215))
        self.filename_le.setReadOnly(False)
        self.filename_le.setObjectName("filename_le")
        self.horizontalLayout_2.addWidget(self.filename_le)
        self.editName_chk = QtWidgets.QCheckBox(playblast_dlg)
        self.editName_chk.setObjectName("editName_chk")
        self.horizontalLayout_2.addWidget(self.editName_chk)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.label_5 = QtWidgets.QLabel(playblast_dlg)
        self.label_5.setMinimumSize(QtCore.QSize(120, 0))
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.overwrite_chk = QtWidgets.QCheckBox(playblast_dlg)
        self.overwrite_chk.setText("")
        self.overwrite_chk.setObjectName("overwrite_chk")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.overwrite_chk)
        self.line_3 = QtWidgets.QFrame(playblast_dlg)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.line_3)
        self.widthHeight_lbl = QtWidgets.QLabel(playblast_dlg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widthHeight_lbl.sizePolicy().hasHeightForWidth())
        self.widthHeight_lbl.setSizePolicy(sizePolicy)
        self.widthHeight_lbl.setMinimumSize(QtCore.QSize(120, 0))
        self.widthHeight_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.widthHeight_lbl.setObjectName("widthHeight_lbl")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.widthHeight_lbl)
        self.widthHeight_hlt = QtWidgets.QHBoxLayout()
        self.widthHeight_hlt.setSpacing(4)
        self.widthHeight_hlt.setObjectName("widthHeight_hlt")
        self.width_le = QtWidgets.QLineEdit(playblast_dlg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.width_le.sizePolicy().hasHeightForWidth())
        self.width_le.setSizePolicy(sizePolicy)
        self.width_le.setMaximumSize(QtCore.QSize(50, 16777215))
        self.width_le.setText("")
        self.width_le.setObjectName("width_le")
        self.widthHeight_hlt.addWidget(self.width_le)
        self.height_le = QtWidgets.QLineEdit(playblast_dlg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.height_le.sizePolicy().hasHeightForWidth())
        self.height_le.setSizePolicy(sizePolicy)
        self.height_le.setMaximumSize(QtCore.QSize(50, 16777215))
        self.height_le.setText("")
        self.height_le.setObjectName("height_le")
        self.widthHeight_hlt.addWidget(self.height_le)
        self.loadRender_btn = QtWidgets.QPushButton(playblast_dlg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadRender_btn.sizePolicy().hasHeightForWidth())
        self.loadRender_btn.setSizePolicy(sizePolicy)
        self.loadRender_btn.setMinimumSize(QtCore.QSize(0, 25))
        self.loadRender_btn.setFlat(False)
        self.loadRender_btn.setObjectName("loadRender_btn")
        self.widthHeight_hlt.addWidget(self.loadRender_btn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.widthHeight_hlt.addItem(spacerItem)
        self.formLayout.setLayout(4, QtWidgets.QFormLayout.FieldRole, self.widthHeight_hlt)
        self.startEnd_lbl = QtWidgets.QLabel(playblast_dlg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startEnd_lbl.sizePolicy().hasHeightForWidth())
        self.startEnd_lbl.setSizePolicy(sizePolicy)
        self.startEnd_lbl.setMinimumSize(QtCore.QSize(120, 0))
        self.startEnd_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.startEnd_lbl.setObjectName("startEnd_lbl")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.startEnd_lbl)
        self.startEnd_hlt = QtWidgets.QHBoxLayout()
        self.startEnd_hlt.setSpacing(4)
        self.startEnd_hlt.setObjectName("startEnd_hlt")
        self.start_le = QtWidgets.QLineEdit(playblast_dlg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start_le.sizePolicy().hasHeightForWidth())
        self.start_le.setSizePolicy(sizePolicy)
        self.start_le.setMaximumSize(QtCore.QSize(50, 16777215))
        self.start_le.setObjectName("start_le")
        self.startEnd_hlt.addWidget(self.start_le)
        self.end_le = QtWidgets.QLineEdit(playblast_dlg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.end_le.sizePolicy().hasHeightForWidth())
        self.end_le.setSizePolicy(sizePolicy)
        self.end_le.setMaximumSize(QtCore.QSize(50, 16777215))
        self.end_le.setObjectName("end_le")
        self.startEnd_hlt.addWidget(self.end_le)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.startEnd_hlt.addItem(spacerItem1)
        self.formLayout.setLayout(5, QtWidgets.QFormLayout.FieldRole, self.startEnd_hlt)
        self.line = QtWidgets.QFrame(playblast_dlg)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.line)
        self.label = QtWidgets.QLabel(playblast_dlg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(120, 0))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.hud_chk = QtWidgets.QCheckBox(playblast_dlg)
        self.hud_chk.setChecked(False)
        self.hud_chk.setObjectName("hud_chk")
        self.horizontalLayout.addWidget(self.hud_chk)
        self.frameHud_chk = QtWidgets.QCheckBox(playblast_dlg)
        self.frameHud_chk.setObjectName("frameHud_chk")
        self.horizontalLayout.addWidget(self.frameHud_chk)
        self.formLayout.setLayout(8, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.label_2 = QtWidgets.QLabel(playblast_dlg)
        self.label_2.setMinimumSize(QtCore.QSize(120, 0))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.cstmHud_hlt = QtWidgets.QHBoxLayout()
        self.cstmHud_hlt.setSpacing(4)
        self.cstmHud_hlt.setObjectName("cstmHud_hlt")
        self.cstmHud_chk = QtWidgets.QCheckBox(playblast_dlg)
        self.cstmHud_chk.setText("")
        self.cstmHud_chk.setObjectName("cstmHud_chk")
        self.cstmHud_hlt.addWidget(self.cstmHud_chk)
        self.cstmHud_le = QtWidgets.QLineEdit(playblast_dlg)
        self.cstmHud_le.setEnabled(True)
        self.cstmHud_le.setText("")
        self.cstmHud_le.setObjectName("cstmHud_le")
        self.cstmHud_hlt.addWidget(self.cstmHud_le)
        self.formLayout.setLayout(9, QtWidgets.QFormLayout.FieldRole, self.cstmHud_hlt)
        self.line_2 = QtWidgets.QFrame(playblast_dlg)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.line_2)
        self.label_3 = QtWidgets.QLabel(playblast_dlg)
        self.label_3.setMinimumSize(QtCore.QSize(120, 0))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.clearViewport_chk = QtWidgets.QCheckBox(playblast_dlg)
        self.clearViewport_chk.setText("")
        self.clearViewport_chk.setChecked(False)
        self.clearViewport_chk.setObjectName("clearViewport_chk")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.clearViewport_chk)
        self.label_6 = QtWidgets.QLabel(playblast_dlg)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.cam_chk = QtWidgets.QCheckBox(playblast_dlg)
        self.cam_chk.setText("")
        self.cam_chk.setObjectName("cam_chk")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.cam_chk)
        self.label_4 = QtWidgets.QLabel(playblast_dlg)
        self.label_4.setMinimumSize(QtCore.QSize(120, 0))
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(10)
        self.horizontalLayout_4.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.green_chk = QtWidgets.QCheckBox(playblast_dlg)
        self.green_chk.setText("")
        self.green_chk.setObjectName("green_chk")
        self.horizontalLayout_4.addWidget(self.green_chk)
        self.color_btn = QtWidgets.QPushButton(playblast_dlg)
        self.color_btn.setText("")
        self.color_btn.setObjectName("color_btn")
        self.horizontalLayout_4.addWidget(self.color_btn)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.formLayout.setLayout(13, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_4)
        self.label_7 = QtWidgets.QLabel(playblast_dlg)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.offscreen_chk = QtWidgets.QCheckBox(playblast_dlg)
        self.offscreen_chk.setText("")
        self.offscreen_chk.setObjectName("offscreen_chk")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.offscreen_chk)
        self.playblast_vlt.addLayout(self.formLayout)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.playblast_vlt.addItem(spacerItem3)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.playblast_btn = QtWidgets.QPushButton(playblast_dlg)
        self.playblast_btn.setObjectName("playblast_btn")
        self.horizontalLayout_3.addWidget(self.playblast_btn)
        self.reset_btn = QtWidgets.QPushButton(playblast_dlg)
        self.reset_btn.setMaximumSize(QtCore.QSize(150, 16777215))
        self.reset_btn.setObjectName("reset_btn")
        self.horizontalLayout_3.addWidget(self.reset_btn)
        self.playblast_vlt.addLayout(self.horizontalLayout_3)
        self.main_vlt.addLayout(self.playblast_vlt)
        self.filename_lbl.setBuddy(self.filename_le)
        self.widthHeight_lbl.setBuddy(self.width_le)
        self.startEnd_lbl.setBuddy(self.start_le)

        self.retranslateUi(playblast_dlg)
        QtCore.QMetaObject.connectSlotsByName(playblast_dlg)

    def retranslateUi(self, playblast_dlg):
        playblast_dlg.setWindowTitle(QtWidgets.QApplication.translate("playblast_dlg", "Playblast-O-Scope", None, -1))
        self.title_lbl.setText(QtWidgets.QApplication.translate("playblast_dlg", "-- Playblast-O-Scope --", None, -1))
        self.filename_lbl.setText(QtWidgets.QApplication.translate("playblast_dlg", "Filename:", None, -1))
        self.editName_chk.setText(QtWidgets.QApplication.translate("playblast_dlg", "Edit", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("playblast_dlg", "Overwrite:", None, -1))
        self.widthHeight_lbl.setText(QtWidgets.QApplication.translate("playblast_dlg", "Width/Height:", None, -1))
        self.loadRender_btn.setText(QtWidgets.QApplication.translate("playblast_dlg", "Load Render Settings", None, -1))
        self.startEnd_lbl.setText(QtWidgets.QApplication.translate("playblast_dlg", "Start/End Frame:", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("playblast_dlg", "HUD Scene Info:", None, -1))
        self.hud_chk.setText(QtWidgets.QApplication.translate("playblast_dlg", "Project and Scene Name", None, -1))
        self.frameHud_chk.setText(QtWidgets.QApplication.translate("playblast_dlg", "Frame Counter", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("playblast_dlg", "HUD User Name:", None, -1))
        self.cstmHud_le.setPlaceholderText(QtWidgets.QApplication.translate("playblast_dlg", "Enter Name...", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("playblast_dlg", "Only Show Polygons:", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("playblast_dlg", "Hide Camera Gate:", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("playblast_dlg", "Set BG Color:", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("playblast_dlg", "Playblast Offscreen:", None, -1))
        self.playblast_btn.setText(QtWidgets.QApplication.translate("playblast_dlg", "Playblast!", None, -1))
        self.reset_btn.setText(QtWidgets.QApplication.translate("playblast_dlg", "Reset", None, -1))

